GesturesTrainer/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('exercises.urls', namespace = "exercises")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    ]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# social oauth
urlpatterns.append(url('', include('social.apps.django_app.urls', namespace='social')))

urlpatterns = i18n_patterns(*urlpatterns)

exercises/urls.py
from django.conf.urls import url, include
from exercises import views
from rest_framework.routers import DefaultRouter
from django.contrib.auth.views import login
from django.contrib.auth.decorators import user_passes_test


login_forbidden =  user_passes_test(lambda u: u.is_anonymous(), '/')



urlpatterns = [
    url(r'^login$', login_forbidden(login),{'template_name': 'exercises/login.html' }, name="login"),
    # url(r'^$', 'django.contrib.auth.views.login',{'template_name': 'exercises/login.html'}, name='login'),
    url(r'^$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^exercise$', views.ExerciseView.as_view(), name='exercise'),
    url(r'^userResponse$', views.UserResponseView.as_view(), name='userResponse'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name = 'logout'),
]

exercises/views.py
from exercises.models import ExerciseResult, Phase, Section, PhaseSection, QUESTIONS, VIDEOS, P3_VIDEO_CUTOFF
from rest_framework import generics, permissions

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.views import generic
from django.shortcuts import render
from django.db.models import Avg, Max, Min, Count
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy

from exercises.permissions import IsOwnerOrReadOnly
from rest_framework.decorators import api_view, detail_route
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework import renderers
from rest_framework import viewsets
from random import sample
import json, ast
from datetime import date, timedelta, datetime
from django.utils import timezone



def logged_in_and_in_group(user):
  r = False
  if user.is_authenticated():
    # current requirement only requires user to be authenticated to be able to use the site
    r = True

    # # group that user needs to be in
    # if user.groups.filter(name='patientGroup').exists():
    #   r = True
  return r

class GroupRequiredMixin(object): 
  # path to be redirected when user is not logged in yet
  login_url = reverse_lazy('exercises:login')
  
  @method_decorator(user_passes_test(logged_in_and_in_group, login_url=login_url))
  def dispatch(self, *args, **kwargs):
    return super(GroupRequiredMixin, self).dispatch(*args, **kwargs)

class DashboardView(GroupRequiredMixin, generic.View):
  """
  DashboardView is the first view after login the user sees, which contains all the sections available as buttons
  All exercises should be displayed as buttons
  Only exercises that are accessible should be enabled
  Otherwise, exercises that are not accessible should be disabled


  """



  def get(self, request):


    a = Exercise(user = request.user)

    sectionsAvailable =  a.sectionsAvailable()
    response = {"all_sections": sectionsAvailable}
    
    if request.user.groups.filter(name='debug').exists():
            response['debug'] = True



    return render(request,'exercises/dashboard.html', 
         response
      )

class UserResponseView(GroupRequiredMixin, generic.View):
    """
    UserResponseView handles user response when user picks a choice on ExerciseView
    """

    def post(self, request):

        # print 'response posted......', request.POST.get('phase'), request.POST.get('section'), request.POST.get('target'),request.POST.get('choice')
        # insert data into models

        try:
            data = ExerciseResult(
                                owner= request.user,
                                phase = request.POST.get('phase'),
                                section = request.POST.get('section'),
                                gestureTested = request.POST.get('target'),
                                response = request.POST.get('choice'),
                                    )
            data.save()
        except Exception,e: 
            print str(e)
            return HttpResponse(status=200)

        return HttpResponse(status=201)

    def get(self, request):
        # checks user's progess and whether they should exit the section
        a = Exercise(user = request.user)
        phase = request.GET.get('phase')
        section = request.GET.get('section')

        return HttpResponse(json.dumps({'response': a.endCurrentSection(phase, section)}), content_type='application/json')


class ExerciseView(GroupRequiredMixin, generic.View):
    """
    ExerciseView is the actual view that delivers the videos and question choices for the users
    """

    def post(self, request):
        response = {}
        
        a = Exercise(user = request.user)

        print 'dashbtn:', request.POST.get('dashbtn', False)

        phase_section = request.POST.get('dashbtn', False)
        if phase_section:
            phase_section = phase_section.split(',')
            phase = phase_section[0]
            section = phase_section[1]
            self.request.session['dashbtn'] = {'phase':phase, 'section': section}
        else:
            # phase_section = ast.literal_eval(request.POST.get('dashbtn', 'False'))
            phase_section = self.request.session['dashbtn'] 
            phase = phase_section['phase']
            section = phase_section['section']


        # if user clicked understandBtn, user understands the instruction video, update cookies and proceed to questions
        if request.POST.get('understandBtn', False) == '1':
            self.request.session['watched_instruction_already_{}_{}'.format(phase, section)] = True


        print 'phase_section: ', phase_section, phase, section

        print 'request.session', self.request.session

        greetings_and_instruction = None
        generateQuestion = None


        if 'watched_instruction_already_{}_{}'.format(phase, section) in self.request.session.keys() and self.request.session['watched_instruction_already_{}_{}'.format(phase, section)] == True:
            # user has watched instruction and greeting videos, proceed to generating question
            response['watched_instruction_already'] = True
            response['generateQuestion'] = a.generateQuestion(phase, section)
        else:
            # user hasn't watched instructions yet, redirect to instruction and greeting videos
            response['watched_instruction_already'] = False
            response['generateInstruction'] = a.generateInstruction(phase, section)
            




        response['request'] = self.request.session.keys()
        response['phase'] = phase
        response['section'] = section
        # response['robothead_small_image'] = 'https://s3-ap-southeast-1.amazonaws.com/gesturetrainingmedia/robothead_small.png'
        response['robothead_small_image'] = ''


        if request.user.groups.filter(name='debug').exists():
            response['debug'] = True

        return render(request,'exercises/exercise.html', 
        response
          )



phase_ordered_list = [
    'phase1',
    'phase2',
    'phase3',
]

section_ordered_list = [
    'pretest',
    'training1',
    'training2',
    'training3',
    'training4',
    'posttest1',
    'posttest2',
    'posttest3',
]

class Exercise(object):
    """Abstract class for a exercise or question"""
    def __init__(self, user):
        self.user = user


    def sectionsAvailable(self):
        """
        returns sections <array> that are open to the user based on the progress of the user
        """

        q = ExerciseResult.objects.filter(owner = self.user)
        # select count from exercises where user = user, group by section
        q = q.values('phase','section').annotate(Count('owner')).values_list('phase','section', 'owner__count')
 
        # initialize user progress with all 0s, place it in <dict> for easy update
        user_progress = {}
        for i in phase_ordered_list:
            user_progress[i] = {}
            for j in section_ordered_list:
                user_progress[i][j] = 0

        # update count from DB
        for i in q:
            user_progress[i[0]][i[1]] = i[2]

        q = PhaseSection.objects.all().values_list('phase','section','start_date')

        phaseSection_start_dates = {}
        for i in phase_ordered_list:
            phaseSection_start_dates[i] = {}
            for j in section_ordered_list:
                phaseSection_start_dates[i][j] = 0

        # update count from DB
        for i in q:
            phaseSection_start_dates[i[0]][i[1]] = i[2]


        # check if training2 is complete then update training3 to 1 week after the latest record's completion date
        # for i in phase_ordered_list:
        #     if user_progress[i]['training2'] >= 20:
        #         postponeTime = timedelta(weeks = 1) + ExerciseResult.objects.filter(phase = i, section = 'training2').values_list('created').order_by('-created')[0][0]
        #         if postponeTime > phaseSection_start_dates[i]['training3']:
        #             # if the postponed time is later than the assigned time, then it needs to be updated to one week ahead
        #             phaseSection_start_dates[i]['training3'] = postponeTime

        postponeDays = 0
        latest_completed_date = None
        for i in phase_ordered_list:
            for j in section_ordered_list:
                if latest_completed_date and postponeDays != 0 :
                    # update postponed times if the section has begun
                    postponeTime = timedelta(days = postponeDays) + latest_completed_date['created']
                    
                    if postponeTime > phaseSection_start_dates[i][j]:
                        # if the postponed time is later than the assigned time, then it needs to be updated
                        # print 'postponeTime',i,j, postponeTime
                        phaseSection_start_dates[i][j] = postponeTime
                # reset postponeDays counter
                postponeDays = 0
                if user_progress[i][j] >= 20:
                    postponeDays = PhaseSection.objects.get(phase = i, section = j).days_apart
                    latest_completed_date = ExerciseResult.objects.filter(phase = i, section = j, owner = self.user).values('created').order_by('-created').first()
                   

        # generate a list of dicts and determine whether section should be enabled
        today_date = timezone.now()
        previous_section_complete = True


        results = []
        found_next_section = False
        for i in phase_ordered_list:
            for j in section_ordered_list:
                result = {}
                result['phase'] = i
                result['section'] = j
                result['name'] = i + '_' +j
                result['user_progress'] = user_progress[i][j]

exercises/templates/exercises/_phase1posttest.html
{% load i18n %}
  <p id="phase1posttest"></p>
      <div id="myPlayer"></div>
        <script type="text/javascript">
          var loopCounter = 0;
          var notResponded = true;
          var thePlayer = jwplayer("myPlayer").setup({
                playlist: [
                             {
                                file:"{{generateQuestion.instructionPreGestureVideo}}", 
                                image:"{{robothead_small_image}}",
                              },
                             {
                                file:"{{generateQuestion.targetGestureVideo}}",
                                image:"{{robothead_small_image}}",
                              },
                              {
                                file:"{{generateQuestion.instructionPostGestureVideo}}",
                                image:"{{robothead_small_image}}",
                              },
                              {
                                file:"{{generateQuestion.choiceAVideo}}",
                                image:"{{robothead_small_image}}",
                              },
                              {
                                file:"{{generateQuestion.choiceBVideo}}",
                                image:"{{robothead_small_image}}",
                              },
                              {
                                file:"{{generateQuestion.choiceCVideo}}",
                                image:"{{robothead_small_image}}",
                              },
                              {
                                file:"{{generateQuestion.MakeAChoiceVideo}}",
                                image:"{{robothead_small_image}}",
                              },

                  ],
                  width: "100%",
              aspectratio: "595:576",
              stretching: "exactfit",
              autostart: true,
              events:{ 
                  onTime: function(event) { 
                    if(this.getPlaylistIndex() == 6){
                      if (event.position >= 12 && notResponded) { 
                        $("#choiceABtn, #choiceBBtn, #choiceCBtn, #dunnoBtn").removeClass("disabled");
                      }
                    }
                
                  },
                  onPlaylistComplete:function(){
                    // user timed out, disable choices, timedOut
                    if (loopCounter == 1 || notResponded == false){
                      $("#choiceABtn, #choiceBBtn, #choiceCBtn, #dunnoBtn").addClass("disabled");
                      

                      if (notResponded){
                        var postdata={
                        'choice': 'timedOut',
                        'target':"{{generateQuestion.targetGesture}}",
                        'phase': "{{phase}}",
                        'section': "{{section}}",
                        }
                        $.post('{% url 'exercises:userResponse' %}',postdata).done(
                            function(){
                              // checkProgress(postdata);
                              $("#nextBtn").removeClass("disabled");

                            }

                        


                          );
                      } else {
                        $("#nextBtn").removeClass("disabled");
                      }
                    }
                    else
                    {
                      loopCounter ++;
                      $("#choiceABtn, #choiceBBtn, #choiceCBtn, #dunnoBtn").addClass("disabled");

                      thePlayer.playlistItem(0);
                    }
                    
                    
                    
                  },
                  onPlaylistItem:function(index, playlist){
                    console.log(index["index"]);
                    if (index["index"] == 3){
                      console.log("display A");
                      $("#choiceABtn").html("A. {% trans generateQuestion.choiceA %}");
                    }  else if (index["index"] == 4) {
                      console.log("display B");
                      $("#choiceBBtn").html("B. {% trans generateQuestion.choiceB %}");
                    }  else if (index["index"] == 5) {
                      console.log("display C");
                      $("#choiceCBtn").html("C. {% trans generateQuestion.choiceC %}");
                    }


                  }
                }
              }); 
            //stop player manual controls
              if (isMobile == false) {
                thePlayer.setControls(false);
              }

              thePlayer.on('beforePlay', function(event){
                thePlayer.setControls(false);
              });
              

        $(document).ready(function () {



          $.getScript("/static/js/setcsrf.js", function(){

             console.log("setcrsf.js loaded");

          });

          $("#choiceABtn, #choiceBBtn, #choiceCBtn, #dunnoBtn").click(function(){
            console.log("some button was clicked.");
            notResponded = false;
            var thisbutton = $(this);
            var postdata={
              'choice': $(this).val(),
              'target':"{{generateQuestion.targetGesture}}",
              'phase': "{{phase}}",
              'section': "{{section}}",
            }
            $.post('{% url 'exercises:userResponse' %}',postdata).done(
              // checkProgress(postdata)
                function(){
                  if (thisbutton.val() == "{{generateQuestion.targetGesture}}" ){
                      thePlayer.load([{
                                        file:"{{generateQuestion.FeedbackCorrect}}",
                                        image:"{{robothead_small_image}}",
                                      }
                                    ]);
                  } else {
                      thePlayer.load([{
                                        file:"{{generateQuestion.FeedbackWrong}}",
                                        image:"{{robothead_small_image}}",
                                      }
                                    ]);
                  }

                  if (isMobile == true) {
                    thePlayer.setControls(true);
                  }
                }
              );
            $("#choiceABtn, #choiceBBtn, #choiceCBtn, #dunnoBtn").addClass('disabled');
            

            
            



          });
        });
        </script>





      <div class="row">

          <div class="col-sm-3 btn-vert-block">
              <button type="button" class="btn btn-block btn-primary disabled" id="choiceABtn" name="choiceABtn" value="{{generateQuestion.choiceA}}"> A </button>
          </div>
          <div class="col-sm-3 btn-vert-block">
              <button type="button" class="btn btn-block btn-primary disabled" id="choiceBBtn" name="choiceBBtn" value="{{generateQuestion.choiceB}}"> B </button>
          </div>
          <div class="col-sm-3 btn-vert-block">
              <button type="button" class="btn btn-block btn-primary disabled" id="choiceCBtn" name="choiceCBtn" value="{{generateQuestion.choiceC}}"> C </button>
          </div>
          <div class="col-sm-3 btn-vert-block">
              <button type="button" class="btn btn-block btn-primary disabled" id="dunnoBtn" name="dunnoBtn" value="dontKnow">{% trans "Don't Know" %}</button>
          </div>

      </div>

exercises/templates/exercises/_phase1training.html
{% load i18n %}
     <p id="phase1training"></p>

      <div id="myPlayer"></div>
      <script type="text/javascript">
          var notResponded = true;
          var thePlayer = jwplayer("myPlayer").setup({
                playlist: [
                             {
                                file:"{{generateQuestion.targetGestureVideo}}", 
                                image:"{{robothead_small_image}}",
                              },

                  ],
                  width: "100%",
              aspectratio: "595:576",
              stretching: "exactfit",
              autostart: true,
              events:{ 
                  onTime: function(event) {                 
                  },
                  onPlaylistComplete:function(){
                    // user timed out, disable choices, timedOut
                    console.log("enable buttons");

                    if (notResponded){
                      var postdata={
                      'choice': 'noResponseRequired',
                      'target':"{{generateQuestion.targetGesture}}",
                      'phase': "{{phase}}",
                      'section': "{{section}}",
                      }
                      $.post('{% url 'exercises:userResponse' %}',postdata)
                        .done(function( json ) {
                          $.getJSON('{% url 'exercises:userResponse' %}', postdata)
                            .done(function( json ) {
                              console.log( "JSON Data endCurrentSection?: " + json.response );
                              if (json.response){
                                $("#nextBtn").addClass("disabled hidden");
                                $("#dashBtn").removeClass("disabled hidden");
                              } else {
                                $("#nextBtn").removeClass("disabled");
                              }
                            })
                            .fail(function( jqxhr, textStatus, error ) {
                                var err = textStatus + ", " + error;
                                console.log( "Request Failed: " + err );
                            });


                          });

                      


                     
                      
                    }
                    
                    
                  },
                  onPlaylistItem:function(index, playlist){
                    if (index["index"] == 0){
                      $("#trainingBtn").html("{% trans generateQuestion.targetGesture %}")

                    };
                  
                  }
                }
              });
             
            //stop player manual controls
            if (isMobile == false) {
                thePlayer.setControls(false);
              }

              thePlayer.on('beforePlay', function(event){
                thePlayer.setControls(false);
              });
             

        $(document).ready(function () {



          $.getScript("/static/js/setcsrf.js", function(){

             console.log("setcrsf.js loaded");

          });


        });
        </script>

      <div class="row">
          <div class="col-sm-4 btn-vert-block"></div>
          <div class="col-sm-4 btn-vert-block">
              <button type="submit" class="btn btn-block btn-primary disabled" id="trainingBtn" name="trainingBtn" value="0">{% trans "..." %}</button>
          </div>
          <div class="col-sm-4 btn-vert-block"></div>
      </div>

exercises/templates/exercises/dashboard.html
{% extends 'exercises/layout.html' %}
{% load i18n %}
{% block customScripts %}


{% endblock customScripts %}

{% block custombody_content %}

<div class="container">
<br>

<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8 btn-vert-block">
  
    <form method="post" action="{% url 'exercises:exercise' %}">
      {% csrf_token %}
      
    

      {% for section in all_sections %}

            {% if section.is_enabled %}

              {% if section.phase == "phase1" %}
                <button type="submit" class="btn btn-primary btn-block" name="dashbtn" value="{{section.phase}},{{section.section}}">
                  {% trans section.phase %} {% trans section.section %}
                </button>
              {% endif %}

              {% if section.phase == "phase2" %}
                <button type="submit" class="btn btn-success btn-block" name="dashbtn" value="{{section.phase}},{{section.section}}">
                  {% trans section.phase %} {% trans section.section %}
                </button>
              {% endif %}

              {% if section.phase == "phase3" %}
                <button type="submit" class="btn btn-warning btn-block" name="dashbtn" value="{{section.phase}},{{section.section}}">
                  {% trans section.phase %} {% trans section.section %}
                </button>
              {% endif %}





            {% else %}

              <button class="btn btn-primary btn-block disabled">{% trans section.phase %} {% trans section.section %}</button>

            {% endif %}  
            
            {% if debug %}
              <p> {{section}}</p>
            {% endif %}
            <br>



      {% empty %}
          <p>{% trans "Sorry, no exercises are available to you." %}</p>
      {% endfor %}
    </form>
  </div>
  <div class="col-sm-2"></div>
</div>


</div>
{% endblock custombody_content %}

exercises/templates/exercises/exercise.html
{% extends 'exercises/layout.html' %}
{% load i18n %}
{% block customScripts %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- <script src="http://content.jwplatform.com/libraries/IUkQRbu5.js"></script> -->
<script src="static/js/jwplayer/jwplayer.js"></script>
<script src="static/js/detectMobile.js"></script>
<script>jwplayer.key="u2ChYQ/2ke1y0A+Wyw3UWeTCaZmZx1LLHZnJ5w==";</script>

<script type="text/javascript">
          function checkProgress(postdata) {
                          $.getJSON('{% url 'exercises:userResponse' %}', postdata)
                            .done(function( json ) {
                              console.log( "JSON Data endCurrentSection?: " + json.response );
                              if (json.response){
                                $("#nextBtn").addClass("disabled hidden");
                                $("#dashBtn").removeClass("disabled hidden");
                              }
                            })
                            .fail(function( jqxhr, textStatus, error ) {
                                var err = textStatus + ", " + error;
                                console.log( "Request Failed: " + err );
                            });


                          }

</script>


{% endblock customScripts %}

{% block custombody_content %}

<style type="text/css">
/* As per Catherine requirements to make gesture more bold*/
#trainingBtn, #instructionDisplayBtn  {
  color: red;
  font-weight: bold;
  font-size: larger;
}
</style>

<div class="container">
<br>

<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">

{% if debug %}

<p>video and buttons should go here</p>


<p>phase: {{phase}}</p>
<p>section: {{section}}</p>
<p>watched_instruction_already: {{watched_instruction_already}}</p>
<p>generateInstruction: {{generateInstruction}}</p>
<p>generateQuestion: {{generateQuestion}}</p>
<p>request: {{request}}</p>

{% endif %}



<form method="post" action="{% url 'exercises:exercise' %}">
  {% csrf_token %}

{% if watched_instruction_already == False %}

  <div id="myPlayer"></div>
  <script type="text/javascript">
    var thePlayer = jwplayer("myPlayer").setup({
          playlist: [
                        {
                          file:"{{generateInstruction.greetingVideo}}", 
                          image:"{{robothead_small_image}}",
                        },
                       {
                          file:"{{generateInstruction.doYouUnderstandVideo}}",
                          image:"{{robothead_small_image}}",
                        },
            ],
            width: "100%",
        aspectratio: "595:576",
        stretching: "exactfit",
        autostart: true,
        // events:{ 

        //     onPlaylistComplete:function(){
        //       $('#understandBtn, #dontUnderstandBtn').removeClass('disabled');
        //     }

        //   }
        }); 
      //stop player manual controls
        if (isMobile == false) {
          thePlayer.setControls(false);
        }

        thePlayer.on('beforePlay', function(event){
          thePlayer.setControls(false);
        });

        thePlayer.on('playlistComplete', function(event){
          $('#understandBtn, #dontUnderstandBtn').removeClass('disabled');
        });
  
  </script>




{% if debug %}

<div class="row">
  <div class="col-sm-6 btn-vert-block">
    <button type="submit" class="btn btn-primary btn-block" id="understandBtn" name="understandBtn" value="1">{% trans "I understand" %} </button>
  </div>
  <div class="col-sm-6 btn-vert-block">
    <button type="submit" class="btn btn-primary btn-block" id="dontUnderstandBtn" name="dontUnderstandBtn" value="1">{% trans "I don't understand" %}</button>
  </div>
</div>

{% else %}

<div class="row">
  <div class="col-sm-6 btn-vert-block">
    <button type="submit" class="btn btn-primary btn-block disabled" id="understandBtn" name="understandBtn" value="1">{% trans "I understand" %}</button>
  </div>
  <div class="col-sm-6 btn-vert-block">
    <button type="submit" class="btn btn-primary btn-block disabled" id="dontUnderstandBtn" name="dontUnderstandBtn" value="1">{% trans "I don't understand" %}</button>
  </div>
</div>

{% endif %}

    




{% elif generateQuestion.finishedSection == False %}


  {% if phase == "phase1"%}
    {% if section == "pretest"%}
        
      {% include "exercises/_phase1pretest.html" %}
      
    {% endif %}

    {% if section == "training1" or section == "training2" or section == "training3" or section == "training4" %}

      {% include "exercises/_phase1training.html" %}

    {% endif %}

    {% if section == "posttest1" or section == "posttest2" or section == "posttest3" %}

      {% include "exercises/_phase1posttest.html" %}

    {% endif %}
  {% endif %}

  {% if phase == "phase2"%}
    {% if section == "pretest"%}

      {% include "exercises/_phase2pretest.html" %}


    {% endif %}

    {% if section == "training1" or section == "training2" or section == "training3" or section == "training4" %}

      {% include "exercises/_phase2training.html" %}

    {% endif %}

    {% if section == "posttest1" or section == "posttest2" or section == "posttest3" %}

      {% include "exercises/_phase2posttest.html" %}

    {% endif %}
  {% endif %}

  {% if phase == "phase3"%}
    {% if section == "pretest"%}

      {% include "exercises/_phase3pretest.html" %}

    {% endif %}

    {% if section == "training1" or section == "training2" or section == "training3" or section == "training4" %}

      {% include "exercises/_phase3training.html" %}

    {% endif %}

    {% if section == "posttest1" or section == "posttest2" or section == "posttest3" %}

      {% include "exercises/_phase3posttest.html" %}

    {% endif %}
  {% endif %}

  <br/>
  <div class="row text-center">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
      <button type="submit" class="btn btn-block btn-primary disabled" id="nextBtn" name="nextBtn" value="1">{% trans "Next" %}</button>
    </div>
    <div class="col-sm-4"></div>
  </div>

{% else %}
  <script type="text/javascript">
    $(document).ready(function () {
      console.log('progress_percent is 1 or greater, it is completed force user out')
      // progress_percent is 1 or greater, it is completed force user out
      $("#dashBtn").removeClass("disabled hidden");
    })
  </script>

{% endif %}
  </form>

  <br/>

  <form method="get" action="{% url 'exercises:dashboard' %}">
  {% csrf_token %}
    <div class="row text-center">
      <div class="col-sm-4"></div>
      <div class="col-sm-4">
        <button type="submit" class="btn btn-block btn-primary hidden" id="dashBtn" name="dashBtn" value="1">{% trans "Section is complete" %}</button>
      </div>
      <div class="col-sm-4"></div>
    </div>
  </form>
  





  </div>
  <div class="col-sm-2"></div>
</div>


</div>
{% endblock custombody_content %}